config/routes.rb
Rails.application.routes.draw do
  get 'pages/batman'

  get 'pages/superman'

  get 'pages/batman_vs_superman'

  post 'pages/vota_batman'
  post 'pages/vota_superman'

  root 'pages#batman_vs_superman'

end

app/models/voto.rb
class Voto < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def batman
  end

  def superman
  end

  def batman_vs_superman
  end

  def vota_batman
  	if params[:email].blank?
      User.create(nombre: "Batman",email: params[:email])
      
    end
    redirect_to pages_batman_vs_superman_path,notice: "Votaste por Batman email:#{params[:email]}"
  end
  def vota_superman
  	if params[:email].blank?
      User.create(nombre: "Superman",email: params[:email])
      
    end
    redirect_to pages_batman_vs_superman_path,notice: "Votaste por Superman email:#{params[:email]}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Superheroes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!--Boostrap CSS -->
  <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css', media: 'all', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body id="<%= params[:action] %>">

<%= yield %>


<!--Boostrap JS-->
  <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js'%> 
</body>
</html>

app/views/pages/batman.html.erb
<%= javascript_include_tag "batman_images" %>
<h1>Batman</h1>
<p>"I am Batman"</p>
<%= params %>

app/views/pages/batman_vs_superman.html.erb
<h1>batman_vs_superman</h1>
<div class="alert alert-success">
<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
<%= flash[:notice] %>
</div>
<div class="container-fluid">
<div class="row">
  
  <div id="batman"  class="pgBatmanSuperman col-md-6">
  <a href="<%= pages_batman_path %>">Batman</a>
	<form method="POST" action="<%= pages_vota_batman_path %>">
	<%= hidden_field_tag :authenticity_token,
	form_authenticity_token %>
	<label for="email">email:</label>
 	<input  class="negritas"type="email" name="email">
	<input class="negritas" type="submit" value="Votar">
	</form>
  </div>
  
  
  <div id="superman" class="pgBatmanSuperman col-md-6">
  <a href="<%= pages_superman_path %>">Superman</a>
  	<form method="POST" action="<%= pages_vota_superman_path %>">
	<%= hidden_field_tag :authenticity_token,
	form_authenticity_token %>
	<label for="email">email:</label>
 	<input class="negritas" type="email" name="email">
	<input class="negritas"type="submit" value="Votar">
	</form>
  </div>
  
 </div>
</div>

app/views/pages/superman.html.erb
<%= javascript_include_tag "superman_images" %> 
<h1>Superman</h1>
<p>"This looks like a job for Superman"</p>